# Generated by Django 3.2.5 on 2022-02-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('age', models.IntegerField(max_length=20)),
                ('std', models.CharField(max_length=255)),
                ('marks', models.FloatField(max_length=20)),
            ],
        ),
    ]
